export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_PLANETS = 'FETCH_PLANETS';
export const FETCH_SPACESHIPS = 'FETCH_SPACESHIPS';
export const FIND_FALCONE = 'FIND_FALCONE';
export const UPDATE_SPACESHIP_COUNT = 'UPDATE_SPACESHIP_COUNT';
export const GET_ERROR = 'GET_ERROR';